vlucas/frisby

lib/frisby.js
In the logging class there were some duplication of code. I remove those lines and change the logic. The output will be same with less line of codes.
=> Reduce some unecessary code from the logging method.

lib/frisby.js
=> limit default Content-Type to requests with body

package.json, spec/expects_jsonTypes_spec.js, spec/frisby_spec.js, src/frisby.js, src/frisby/expects.js, src/frisby/spec.js, src/frisby/utils.js
Add Initial `jsonTypes` expect rule using [Joi](https://github.com/hapijs/joi)
=> Initial jsonTypes expect rule using Joi

__tests__/fixtures/http_mocks.js, __tests__/frisby_spec.js, src/frisby/spec.js
=> Add option to fetch() to not auto-encode URLs

src/frisby/spec.js
This PR is a small refactor from #377.
=> Merge setup default headers.

__tests__/frisby_spec.js
=> Fix typo in test.

src/frisby/spec.js, src/frisby/utils.js
=> Remove unused variables.

__tests__/frisby_spec.js, package.json, src/frisby.js
Export FrisbySpec for extension and overriding
=> Export FrisbySpec for extension

src/frisby/spec.js
Added check for status 204, solves my issue and passes your tests.
=> Added check for status 204

src/frisby/spec.js
This PR is a small refactor from #408 and #411.
=> Small refactor from #408 and #411

__tests__/expects_json_spec.js, src/frisby/expects.js
Fix #395 issue.
I thought about ambiguous test expectation of Array.
=> Fix #395 'Array comparisons do not work' issue.

src/frisby.js
=> Change variable statements.

src/frisby/spec.js
=> stop parsing empty response body

src/frisby.js
hello! this is a proposal of frisby.delete() alias #387
=> Add frisby.delete alias

src/frisby/expects.js
options.language.label will be removed at latest version.
change options.language.root.
=> Update joi options.

src/frisby/spec.js
=> Fix #452 'Run expectations even when fetch has been resolved' issue.

__tests__/frisby_spec.js, src/frisby/spec.js
=> Fix #456 'TypeError: Cannot read property 'json' of undefined' issue.

package.json
https://nodesecurity.io/advisories/577
nock
7.7.2 -> 9.3.3(latest)
lodash
4.11.1 -> 4.17.10(latest)
=> Update for security.

README.md, __tests__/expects_json_spec.js, src/frisby/expects.js
=> Allow RegExp in json expect type 

__tests__/file_upload_spec.js, __tests__/frisby_spec.js, src/frisby.js, src/frisby/spec.js
Resolve #436 issue.
- Add rawBody (default: false)
- If rawBody is true, response.body is raw buffer (ArrayBuffer).
=> Resolve #436 'I want to get the raw binary data from response.body' issue.

__tests__/expects_jsonTypes_spec.js, __tests__/expects_json_path_spec.js, __tests__/fixtures/http_mocks.js
- Override joi global options. (ref. #484)
- Test special character &.
=> Add tests.

.travis.yml
Update version list of Node.js.
=> Update Travis CI build file.

__tests__/frisby_spec.js, src/frisby/spec.js
=> Add delete() to FrisbySpec.

__tests__/expects_jsonTypes_spec.js, src/frisby/spec.js, src/frisby/utils.js
Fix #510 issue.(ref. #432 and #433)
- Check if json is undefined or not in json expects.
=> Fix #510 'False positives with body validation' issue.

README.md
I added a ref to the Joi github page in the readme.  I found it was helpful for building custom validators.
=> Updated readme to include references to Joi API

__tests__/fixtures/http_mocks.js, __tests__/frisby_spec.js, src/frisby.js, src/frisby/spec.js
Hi there. I would like to test OPTIONS using frisby. (And I will create PR frisby.head() if this PR is merged)
=> feature: frisby.options()

__tests__/fixtures/http_mocks.js, __tests__/frisby_spec.js, __tests__/nested_spec.js, src/frisby.js, src/frisby/spec.js
Hello, This is a feature request frisby.head() almost same as #521.
=> feature: frisby.head()

.eslintrc.json, .travis.yml, __tests__/expects_jsonTypes_spec.js, __tests__/frisby_spec.js, package.json
Hi there, update devDependencies. And it seems to need to drop node8.
=> Update devDependencies and node 8 to 14

README.md
Added logo from issue comments
=> Added Logo to Readme.md

package.json
=> fix: Allow joi at least 13.7.0

.github/workflows/ci.yml
- test: Test node20 and drop 16
=> test: Test node20 and drop 16

package.json
- chore: Update node-fetch  
- Potentially fix #594 
- chore Upgrade eslint and jest
=> chore: Update node-fetch
